package com.sagaleev.domain.model;

public enum Disease {
    ACUTE_RESPIRATORY_VIRAL_INFECTION,
    MYOCARDIAL_INFARCTION,
    MYOCARDIAL_INFARCTION_WITH_HOSPITALIZATION,
    FATAL_MYOCARDIAL_INFARCTION,
    ANGINA_PECTORIS,
    ARRHYTHMIA,
    CARDIO_VASCULAR_DISEASE,
    FATAL_CARDIO_VASCULAR_DISEASE,
    STROKE,
    FATAL_STROKE,
    PNEUMONIA,
    BRONCHIAL_ASTHMA,
    BRONCHITIS,
    PEPTIC_ULCER_DISEASE,
    GASTRITIS,
}
